server:
  port: 8765
  
  
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  
      
spring:
  application:
    name: api-gateway
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false  


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
